// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dva.queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const closeDVA = `-- name: CloseDVA :exec
UPDATE dedicated_virtual_accounts
SET 
    status = $1,
    closed_at = now(),
    updated_at = now()
WHERE merchant_id = $2 AND subscription_id = $3
RETURNING id, merchant_id, subscription_id, customer_id, customer_name, account_ref, nomba_account_id, bank_account_number, bank_account_name, bank_name, bvn_hash, status, suspended_at, closed_at, created_at, updated_at
`

type CloseDVAParams struct {
	Status         DvaStatus `json:"status"`
	MerchantID     uuid.UUID `json:"merchant_id"`
	SubscriptionID uuid.UUID `json:"subscription_id"`
}

func (q *Queries) CloseDVA(ctx context.Context, arg CloseDVAParams) error {
	_, err := q.db.Exec(ctx, closeDVA, arg.Status, arg.MerchantID, arg.SubscriptionID)
	return err
}

const createDVA = `-- name: CreateDVA :one
INSERT INTO dedicated_virtual_accounts (merchant_id,subscription_id,customer_id,customer_name,account_ref,nomba_account_id,bank_account_number,bank_account_name,bank_name, bvn_hash,status)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9, $10, $11)
RETURNING id, merchant_id, subscription_id, customer_id, customer_name, account_ref, nomba_account_id, bank_account_number, bank_account_name, bank_name, bvn_hash, status, suspended_at, closed_at, created_at, updated_at
`

type CreateDVAParams struct {
	MerchantID        uuid.UUID `json:"merchant_id"`
	SubscriptionID    uuid.UUID `json:"subscription_id"`
	CustomerID        string    `json:"customer_id"`
	CustomerName      string    `json:"customer_name"`
	AccountRef        string    `json:"account_ref"`
	NombaAccountID    *string   `json:"nomba_account_id"`
	BankAccountNumber string    `json:"bank_account_number"`
	BankAccountName   string    `json:"bank_account_name"`
	BankName          string    `json:"bank_name"`
	BvnHash           *string   `json:"bvn_hash"`
	Status            DvaStatus `json:"status"`
}

func (q *Queries) CreateDVA(ctx context.Context, arg CreateDVAParams) (DedicatedVirtualAccount, error) {
	row := q.db.QueryRow(ctx, createDVA,
		arg.MerchantID,
		arg.SubscriptionID,
		arg.CustomerID,
		arg.CustomerName,
		arg.AccountRef,
		arg.NombaAccountID,
		arg.BankAccountNumber,
		arg.BankAccountName,
		arg.BankName,
		arg.BvnHash,
		arg.Status,
	)
	var i DedicatedVirtualAccount
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.CustomerName,
		&i.AccountRef,
		&i.NombaAccountID,
		&i.BankAccountNumber,
		&i.BankAccountName,
		&i.BankName,
		&i.BvnHash,
		&i.Status,
		&i.SuspendedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDVAByAccountRef = `-- name: GetDVAByAccountRef :one
SELECT id, merchant_id, subscription_id, customer_id, customer_name, account_ref, nomba_account_id, bank_account_number, bank_account_name, bank_name, bvn_hash, status, suspended_at, closed_at, created_at, updated_at FROM dedicated_virtual_accounts
WHERE account_ref = $1
LIMIT 1
`

func (q *Queries) GetDVAByAccountRef(ctx context.Context, accountRef string) (DedicatedVirtualAccount, error) {
	row := q.db.QueryRow(ctx, getDVAByAccountRef, accountRef)
	var i DedicatedVirtualAccount
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.CustomerName,
		&i.AccountRef,
		&i.NombaAccountID,
		&i.BankAccountNumber,
		&i.BankAccountName,
		&i.BankName,
		&i.BvnHash,
		&i.Status,
		&i.SuspendedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDVAByID = `-- name: GetDVAByID :one
SELECT id, merchant_id, subscription_id, customer_id, customer_name, account_ref, nomba_account_id, bank_account_number, bank_account_name, bank_name, bvn_hash, status, suspended_at, closed_at, created_at, updated_at FROM dedicated_virtual_accounts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDVAByID(ctx context.Context, id uuid.UUID) (DedicatedVirtualAccount, error) {
	row := q.db.QueryRow(ctx, getDVAByID, id)
	var i DedicatedVirtualAccount
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.CustomerName,
		&i.AccountRef,
		&i.NombaAccountID,
		&i.BankAccountNumber,
		&i.BankAccountName,
		&i.BankName,
		&i.BvnHash,
		&i.Status,
		&i.SuspendedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDVAStatus = `-- name: UpdateDVAStatus :exec
UPDATE dedicated_virtual_accounts
SET status = $1,
    updated_at = now()
WHERE merchant_id = $2 AND subscription_id = $3
RETURNING id, merchant_id, subscription_id, customer_id, customer_name, account_ref, nomba_account_id, bank_account_number, bank_account_name, bank_name, bvn_hash, status, suspended_at, closed_at, created_at, updated_at
`

type UpdateDVAStatusParams struct {
	Status         DvaStatus `json:"status"`
	MerchantID     uuid.UUID `json:"merchant_id"`
	SubscriptionID uuid.UUID `json:"subscription_id"`
}

func (q *Queries) UpdateDVAStatus(ctx context.Context, arg UpdateDVAStatusParams) error {
	_, err := q.db.Exec(ctx, updateDVAStatus, arg.Status, arg.MerchantID, arg.SubscriptionID)
	return err
}
