// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.queries.sql

package db

import (
	"context"
)

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :exec
DELETE
FROM idempotency_keys
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	return err
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
DELETE
FROM idempotency_keys
WHERE idempotency_key = $1
`

func (q *Queries) DeleteIdempotencyKey(ctx context.Context, idempotencyKey string) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyKey, idempotencyKey)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, idempotency_key, request_method, request_path, request_hash, status_code, response_body, created_at, expires_at
FROM idempotency_keys
WHERE idempotency_key = $1
LIMIT 1
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, idempotencyKey string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, idempotencyKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestMethod,
		&i.RequestPath,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const idempotencyKeyExists = `-- name: IdempotencyKeyExists :one
SELECT EXISTS (
    SELECT 1
    FROM idempotency_keys
    WHERE idempotency_key = $1
)
`

func (q *Queries) IdempotencyKeyExists(ctx context.Context, idempotencyKey string) (bool, error) {
	row := q.db.QueryRow(ctx, idempotencyKeyExists, idempotencyKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const storeIdempotencyResponse = `-- name: StoreIdempotencyResponse :one
INSERT INTO idempotency_keys (
    idempotency_key,
    request_method,
    request_path,
    request_hash,
    status_code,
    response_body
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, idempotency_key, request_method, request_path, request_hash, status_code, response_body, created_at, expires_at
`

type StoreIdempotencyResponseParams struct {
	IdempotencyKey string `json:"idempotency_key"`
	RequestMethod  string `json:"request_method"`
	RequestPath    string `json:"request_path"`
	RequestHash    string `json:"request_hash"`
	StatusCode     int32  `json:"status_code"`
	ResponseBody   []byte `json:"response_body"`
}

func (q *Queries) StoreIdempotencyResponse(ctx context.Context, arg StoreIdempotencyResponseParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, storeIdempotencyResponse,
		arg.IdempotencyKey,
		arg.RequestMethod,
		arg.RequestPath,
		arg.RequestHash,
		arg.StatusCode,
		arg.ResponseBody,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RequestMethod,
		&i.RequestPath,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
