// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice.queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (merchant_id,subscription_id,customer_id,invoice_type,total,currency,period_start,period_end,status,payment_method_type,due_date)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, merchant_id, subscription_id, customer_id, invoice_type, total, amount_paid, currency, period_start, period_end, status, payment_method_type, paid_at, due_date, nomba_order_ref, nomba_txn_ref, created_at, updated_at
`

type CreateInvoiceParams struct {
	MerchantID        uuid.UUID          `json:"merchant_id"`
	SubscriptionID    uuid.UUID          `json:"subscription_id"`
	CustomerID        string             `json:"customer_id"`
	InvoiceType       InvoiceType        `json:"invoice_type"`
	Total             int64              `json:"total"`
	Currency          string             `json:"currency"`
	PeriodStart       pgtype.Timestamptz `json:"period_start"`
	PeriodEnd         pgtype.Timestamptz `json:"period_end"`
	Status            InvoiceStatus      `json:"status"`
	PaymentMethodType *string            `json:"payment_method_type"`
	DueDate           pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.MerchantID,
		arg.SubscriptionID,
		arg.CustomerID,
		arg.InvoiceType,
		arg.Total,
		arg.Currency,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Status,
		arg.PaymentMethodType,
		arg.DueDate,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.InvoiceType,
		&i.Total,
		&i.AmountPaid,
		&i.Currency,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.PaymentMethodType,
		&i.PaidAt,
		&i.DueDate,
		&i.NombaOrderRef,
		&i.NombaTxnRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInvoiceOrderRef = `-- name: UpdateInvoiceOrderRef :exec
UPDATE invoices
SET nomba_order_ref = $1
WHERE id = $2
`

type UpdateInvoiceOrderRefParams struct {
	NombaOrderRef *string   `json:"nomba_order_ref"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateInvoiceOrderRef(ctx context.Context, arg UpdateInvoiceOrderRefParams) error {
	_, err := q.db.Exec(ctx, updateInvoiceOrderRef, arg.NombaOrderRef, arg.ID)
	return err
}

const updateInvoicePaymentStatus = `-- name: UpdateInvoicePaymentStatus :one
UPDATE invoices 
SET 
   amount_paid = $1,
   paid_at = $2,
   nomba_order_ref = $3,
   nomba_txn_ref = $4
WHERE merchant_id = $5 AND customer_id = $6
RETURNING id, merchant_id, subscription_id, customer_id, invoice_type, total, amount_paid, currency, period_start, period_end, status, payment_method_type, paid_at, due_date, nomba_order_ref, nomba_txn_ref, created_at, updated_at
`

type UpdateInvoicePaymentStatusParams struct {
	AmountPaid    int64              `json:"amount_paid"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	NombaOrderRef *string            `json:"nomba_order_ref"`
	NombaTxnRef   *string            `json:"nomba_txn_ref"`
	MerchantID    uuid.UUID          `json:"merchant_id"`
	CustomerID    string             `json:"customer_id"`
}

func (q *Queries) UpdateInvoicePaymentStatus(ctx context.Context, arg UpdateInvoicePaymentStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoicePaymentStatus,
		arg.AmountPaid,
		arg.PaidAt,
		arg.NombaOrderRef,
		arg.NombaTxnRef,
		arg.MerchantID,
		arg.CustomerID,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.InvoiceType,
		&i.Total,
		&i.AmountPaid,
		&i.Currency,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.PaymentMethodType,
		&i.PaidAt,
		&i.DueDate,
		&i.NombaOrderRef,
		&i.NombaTxnRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoices
SET 
   status = $1,
   updated_at = now()
WHERE merchant_id = $2 AND customer_id = $3
RETURNING id, merchant_id, subscription_id, customer_id, invoice_type, total, amount_paid, currency, period_start, period_end, status, payment_method_type, paid_at, due_date, nomba_order_ref, nomba_txn_ref, created_at, updated_at
`

type UpdateInvoiceStatusParams struct {
	Status     InvoiceStatus `json:"status"`
	MerchantID uuid.UUID     `json:"merchant_id"`
	CustomerID string        `json:"customer_id"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus, arg.Status, arg.MerchantID, arg.CustomerID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.InvoiceType,
		&i.Total,
		&i.AmountPaid,
		&i.Currency,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.PaymentMethodType,
		&i.PaidAt,
		&i.DueDate,
		&i.NombaOrderRef,
		&i.NombaTxnRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
