// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchant.queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeMerchantProfileOnboarding = `-- name: CompleteMerchantProfileOnboarding :one
UPDATE merchants
SET
    phone_number = $1,
    business_name = $2,
    buisness_type = $3,
    website_url = $4,
    status = $5
WHERE id = $6
RETURNING id, personal_name, password, email, phone_number, business_name, buisness_type, website_url, status, kyb_tier, created_at, updated_at, email_verified
`

type CompleteMerchantProfileOnboardingParams struct {
	PhoneNumber  *string               `json:"phone_number"`
	BusinessName *string               `json:"business_name"`
	BuisnessType NullBuisnessType      `json:"buisness_type"`
	WebsiteUrl   *string               `json:"website_url"`
	Status       MerchantAccountStatus `json:"status"`
	ID           uuid.UUID             `json:"id"`
}

func (q *Queries) CompleteMerchantProfileOnboarding(ctx context.Context, arg CompleteMerchantProfileOnboardingParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, completeMerchantProfileOnboarding,
		arg.PhoneNumber,
		arg.BusinessName,
		arg.BuisnessType,
		arg.WebsiteUrl,
		arg.Status,
		arg.ID,
	)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.PersonalName,
		&i.Password,
		&i.Email,
		&i.PhoneNumber,
		&i.BusinessName,
		&i.BuisnessType,
		&i.WebsiteUrl,
		&i.Status,
		&i.KybTier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerified,
	)
	return i, err
}

const createEmailVerificationCode = `-- name: CreateEmailVerificationCode :one
INSERT INTO merchant_email_verification_codes (merchant_id, email, code, expires_at) 
VALUES ($1, $2, $3, $4)
RETURNING id, merchant_id, email, code, expires_at, verified, created_at
`

type CreateEmailVerificationCodeParams struct {
	MerchantID uuid.UUID        `json:"merchant_id"`
	Email      string           `json:"email"`
	Code       string           `json:"code"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateEmailVerificationCode(ctx context.Context, arg CreateEmailVerificationCodeParams) (MerchantEmailVerificationCode, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationCode,
		arg.MerchantID,
		arg.Email,
		arg.Code,
		arg.ExpiresAt,
	)
	var i MerchantEmailVerificationCode
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const createMerchantApiKeys = `-- name: CreateMerchantApiKeys :one
INSERT INTO merchants_api_keys (merchant_id,key_hash,key_prefix,environment,label)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, merchant_id, key_hash, key_prefix, environment, label, last_used_at, revoked, revoked_at, created_at
`

type CreateMerchantApiKeysParams struct {
	MerchantID  pgtype.UUID `json:"merchant_id"`
	KeyHash     string      `json:"key_hash"`
	KeyPrefix   string      `json:"key_prefix"`
	Environment string      `json:"environment"`
	Label       *string     `json:"label"`
}

func (q *Queries) CreateMerchantApiKeys(ctx context.Context, arg CreateMerchantApiKeysParams) (MerchantsApiKey, error) {
	row := q.db.QueryRow(ctx, createMerchantApiKeys,
		arg.MerchantID,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Environment,
		arg.Label,
	)
	var i MerchantsApiKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Environment,
		&i.Label,
		&i.LastUsedAt,
		&i.Revoked,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMerchantPortalConfig = `-- name: CreateMerchantPortalConfig :one
INSERT INTO merchants_portal_config (merchant_id, logo_url, primary_color, secondary_color, support_email, return_url, smart_retry_enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, merchant_id, logo_url, primary_color, secondary_color, support_email, return_url, smart_retry_enabled, created_at, updated_at
`

type CreateMerchantPortalConfigParams struct {
	MerchantID        pgtype.UUID `json:"merchant_id"`
	LogoUrl           *string     `json:"logo_url"`
	PrimaryColor      *string     `json:"primary_color"`
	SecondaryColor    *string     `json:"secondary_color"`
	SupportEmail      *string     `json:"support_email"`
	ReturnUrl         *string     `json:"return_url"`
	SmartRetryEnabled pgtype.Bool `json:"smart_retry_enabled"`
}

func (q *Queries) CreateMerchantPortalConfig(ctx context.Context, arg CreateMerchantPortalConfigParams) (MerchantsPortalConfig, error) {
	row := q.db.QueryRow(ctx, createMerchantPortalConfig,
		arg.MerchantID,
		arg.LogoUrl,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.SupportEmail,
		arg.ReturnUrl,
		arg.SmartRetryEnabled,
	)
	var i MerchantsPortalConfig
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.SupportEmail,
		&i.ReturnUrl,
		&i.SmartRetryEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMerchantSplitConfig = `-- name: CreateMerchantSplitConfig :one
INSERT INTO merchants_split_config (merchant_id, label, recepient_type, nomba_account_id, split_type, value, active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, merchant_id, label, recepient_type, nomba_account_id, split_type, value, active, created_at, updated_at
`

type CreateMerchantSplitConfigParams struct {
	MerchantID     pgtype.UUID `json:"merchant_id"`
	Label          string      `json:"label"`
	RecepientType  string      `json:"recepient_type"`
	NombaAccountID *string     `json:"nomba_account_id"`
	SplitType      string      `json:"split_type"`
	Value          int64       `json:"value"`
	Active         bool        `json:"active"`
}

func (q *Queries) CreateMerchantSplitConfig(ctx context.Context, arg CreateMerchantSplitConfigParams) (MerchantsSplitConfig, error) {
	row := q.db.QueryRow(ctx, createMerchantSplitConfig,
		arg.MerchantID,
		arg.Label,
		arg.RecepientType,
		arg.NombaAccountID,
		arg.SplitType,
		arg.Value,
		arg.Active,
	)
	var i MerchantsSplitConfig
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Label,
		&i.RecepientType,
		&i.NombaAccountID,
		&i.SplitType,
		&i.Value,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMerchantWebhookConfig = `-- name: CreateMerchantWebhookConfig :one
INSERT INTO merchants_webhook_urls (merchant_id, webhook_url, webhook_secret)
VALUES ($1, $2, $3)
RETURNING id, merchant_id, webhook_url, webhook_secret, created_at, updated_at
`

type CreateMerchantWebhookConfigParams struct {
	MerchantID    pgtype.UUID `json:"merchant_id"`
	WebhookUrl    string      `json:"webhook_url"`
	WebhookSecret string      `json:"webhook_secret"`
}

func (q *Queries) CreateMerchantWebhookConfig(ctx context.Context, arg CreateMerchantWebhookConfigParams) (MerchantsWebhookUrl, error) {
	row := q.db.QueryRow(ctx, createMerchantWebhookConfig, arg.MerchantID, arg.WebhookUrl, arg.WebhookSecret)
	var i MerchantsWebhookUrl
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNewMerchant = `-- name: CreateNewMerchant :one
INSERT INTO merchants (personal_name,password,email)
VALUES ($1, $2, $3)
RETURNING id, personal_name, password, email, phone_number, business_name, buisness_type, website_url, status, kyb_tier, created_at, updated_at, email_verified
`

type CreateNewMerchantParams struct {
	PersonalName string `json:"personal_name"`
	Password     string `json:"password"`
	Email        string `json:"email"`
}

func (q *Queries) CreateNewMerchant(ctx context.Context, arg CreateNewMerchantParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, createNewMerchant, arg.PersonalName, arg.Password, arg.Email)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.PersonalName,
		&i.Password,
		&i.Email,
		&i.PhoneNumber,
		&i.BusinessName,
		&i.BuisnessType,
		&i.WebsiteUrl,
		&i.Status,
		&i.KybTier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerified,
	)
	return i, err
}

const createSettlementAccount = `-- name: CreateSettlementAccount :one
INSERT INTO merchants_settlement_accounts (merchant_id,bank_name,account_number,account_name,bank_code,verified,verified_at,is_primary)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, merchant_id, bank_name, account_number, account_name, bank_code, verified, verified_at, is_primary, created_at, updated_at
`

type CreateSettlementAccountParams struct {
	MerchantID    pgtype.UUID        `json:"merchant_id"`
	BankName      string             `json:"bank_name"`
	AccountNumber string             `json:"account_number"`
	AccountName   string             `json:"account_name"`
	BankCode      string             `json:"bank_code"`
	Verified      bool               `json:"verified"`
	VerifiedAt    pgtype.Timestamptz `json:"verified_at"`
	IsPrimary     bool               `json:"is_primary"`
}

func (q *Queries) CreateSettlementAccount(ctx context.Context, arg CreateSettlementAccountParams) (MerchantsSettlementAccount, error) {
	row := q.db.QueryRow(ctx, createSettlementAccount,
		arg.MerchantID,
		arg.BankName,
		arg.AccountNumber,
		arg.AccountName,
		arg.BankCode,
		arg.Verified,
		arg.VerifiedAt,
		arg.IsPrimary,
	)
	var i MerchantsSettlementAccount
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.BankName,
		&i.AccountNumber,
		&i.AccountName,
		&i.BankCode,
		&i.Verified,
		&i.VerifiedAt,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMerchantSplitConfig = `-- name: DeleteMerchantSplitConfig :one
DELETE FROM merchants_split_config WHERE id = $1 AND merchant_id = $2
RETURNING id, merchant_id, label, recepient_type, nomba_account_id, split_type, value, active, created_at, updated_at
`

type DeleteMerchantSplitConfigParams struct {
	ID         uuid.UUID   `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) DeleteMerchantSplitConfig(ctx context.Context, arg DeleteMerchantSplitConfigParams) (MerchantsSplitConfig, error) {
	row := q.db.QueryRow(ctx, deleteMerchantSplitConfig, arg.ID, arg.MerchantID)
	var i MerchantsSplitConfig
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Label,
		&i.RecepientType,
		&i.NombaAccountID,
		&i.SplitType,
		&i.Value,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveMerchantKeys = `-- name: GetActiveMerchantKeys :one
SELECT id, merchant_id, key_hash, key_prefix, environment, label, last_used_at, revoked, revoked_at, created_at FROM merchants_api_keys WHERE merchant_id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetActiveMerchantKeys(ctx context.Context, merchantID pgtype.UUID) (MerchantsApiKey, error) {
	row := q.db.QueryRow(ctx, getActiveMerchantKeys, merchantID)
	var i MerchantsApiKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Environment,
		&i.Label,
		&i.LastUsedAt,
		&i.Revoked,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailVerificationCode = `-- name: GetEmailVerificationCode :one
SELECT id, merchant_id, email, code, expires_at, verified, created_at
FROM merchant_email_verification_codes
WHERE email = $1
  AND code = $2
  AND expires_at > NOW()
LIMIT 1
`

type GetEmailVerificationCodeParams struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

func (q *Queries) GetEmailVerificationCode(ctx context.Context, arg GetEmailVerificationCodeParams) (MerchantEmailVerificationCode, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationCode, arg.Email, arg.Code)
	var i MerchantEmailVerificationCode
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailVerificationStatus = `-- name: GetEmailVerificationStatus :one
SELECT email_verified FROM merchants WHERE id = $1
`

func (q *Queries) GetEmailVerificationStatus(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationStatus, id)
	var email_verified bool
	err := row.Scan(&email_verified)
	return email_verified, err
}

const getMerchantApiKey = `-- name: GetMerchantApiKey :one
SELECT id, merchant_id, key_hash, key_prefix, environment, label, last_used_at, revoked, revoked_at, created_at FROM merchants_api_keys
WHERE key_hash = $1 AND revoked = false
`

func (q *Queries) GetMerchantApiKey(ctx context.Context, keyHash string) (MerchantsApiKey, error) {
	row := q.db.QueryRow(ctx, getMerchantApiKey, keyHash)
	var i MerchantsApiKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Environment,
		&i.Label,
		&i.LastUsedAt,
		&i.Revoked,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchantByEmail = `-- name: GetMerchantByEmail :one
SELECT id, personal_name, password, email, phone_number, business_name, buisness_type, website_url, status, kyb_tier, created_at, updated_at, email_verified FROM merchants WHERE email = $1
`

func (q *Queries) GetMerchantByEmail(ctx context.Context, email string) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByEmail, email)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.PersonalName,
		&i.Password,
		&i.Email,
		&i.PhoneNumber,
		&i.BusinessName,
		&i.BuisnessType,
		&i.WebsiteUrl,
		&i.Status,
		&i.KybTier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerified,
	)
	return i, err
}

const getMerchantById = `-- name: GetMerchantById :one
SELECT id, personal_name, password, email, phone_number, business_name, buisness_type, website_url, status, kyb_tier, created_at, updated_at, email_verified FROM merchants WHERE id = $1
`

func (q *Queries) GetMerchantById(ctx context.Context, id uuid.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantById, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.PersonalName,
		&i.Password,
		&i.Email,
		&i.PhoneNumber,
		&i.BusinessName,
		&i.BuisnessType,
		&i.WebsiteUrl,
		&i.Status,
		&i.KybTier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerified,
	)
	return i, err
}

const getMerchantKybTier = `-- name: GetMerchantKybTier :one
SELECT kyb_tier FROM merchants WHERE id = $1
`

func (q *Queries) GetMerchantKybTier(ctx context.Context, id uuid.UUID) (KybTier, error) {
	row := q.db.QueryRow(ctx, getMerchantKybTier, id)
	var kyb_tier KybTier
	err := row.Scan(&kyb_tier)
	return kyb_tier, err
}

const getMerchantPortalConfig = `-- name: GetMerchantPortalConfig :one
SELECT id, merchant_id, logo_url, primary_color, secondary_color, support_email, return_url, smart_retry_enabled, created_at, updated_at FROM merchants_portal_config WHERE merchant_id = $1 LIMIT 1
`

func (q *Queries) GetMerchantPortalConfig(ctx context.Context, merchantID pgtype.UUID) (MerchantsPortalConfig, error) {
	row := q.db.QueryRow(ctx, getMerchantPortalConfig, merchantID)
	var i MerchantsPortalConfig
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.SupportEmail,
		&i.ReturnUrl,
		&i.SmartRetryEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMerchantSettlementAccounts = `-- name: GetMerchantSettlementAccounts :many
SELECT id, merchant_id, bank_name, account_number, account_name, bank_code, verified, verified_at, is_primary, created_at, updated_at FROM merchants_settlement_accounts WHERE merchant_id = $1
`

func (q *Queries) GetMerchantSettlementAccounts(ctx context.Context, merchantID pgtype.UUID) ([]MerchantsSettlementAccount, error) {
	rows, err := q.db.Query(ctx, getMerchantSettlementAccounts, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MerchantsSettlementAccount{}
	for rows.Next() {
		var i MerchantsSettlementAccount
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.BankName,
			&i.AccountNumber,
			&i.AccountName,
			&i.BankCode,
			&i.Verified,
			&i.VerifiedAt,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMerchantSplitConfigById = `-- name: GetMerchantSplitConfigById :one
SELECT id, merchant_id, label, recepient_type, nomba_account_id, split_type, value, active, created_at, updated_at FROM merchants_split_config WHERE id = $1 AND merchant_id = $2
`

type GetMerchantSplitConfigByIdParams struct {
	ID         uuid.UUID   `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) GetMerchantSplitConfigById(ctx context.Context, arg GetMerchantSplitConfigByIdParams) (MerchantsSplitConfig, error) {
	row := q.db.QueryRow(ctx, getMerchantSplitConfigById, arg.ID, arg.MerchantID)
	var i MerchantsSplitConfig
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Label,
		&i.RecepientType,
		&i.NombaAccountID,
		&i.SplitType,
		&i.Value,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMerchantSplitConfigs = `-- name: GetMerchantSplitConfigs :many
SELECT id, merchant_id, label, recepient_type, nomba_account_id, split_type, value, active, created_at, updated_at FROM merchants_split_config WHERE merchant_id = $1
`

func (q *Queries) GetMerchantSplitConfigs(ctx context.Context, merchantID pgtype.UUID) ([]MerchantsSplitConfig, error) {
	rows, err := q.db.Query(ctx, getMerchantSplitConfigs, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MerchantsSplitConfig{}
	for rows.Next() {
		var i MerchantsSplitConfig
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Label,
			&i.RecepientType,
			&i.NombaAccountID,
			&i.SplitType,
			&i.Value,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMerchantWebhookConfig = `-- name: GetMerchantWebhookConfig :one
SELECT id, merchant_id, webhook_url, webhook_secret, created_at, updated_at FROM merchants_webhook_urls WHERE merchant_id = $1 LIMIT 1
`

func (q *Queries) GetMerchantWebhookConfig(ctx context.Context, merchantID pgtype.UUID) (MerchantsWebhookUrl, error) {
	row := q.db.QueryRow(ctx, getMerchantWebhookConfig, merchantID)
	var i MerchantsWebhookUrl
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAllMerchantApiKeys = `-- name: RevokeAllMerchantApiKeys :exec
UPDATE merchants_api_keys
SET revoked = true, revoked_at = now()
WHERE merchant_id = $1 AND revoked = false
`

func (q *Queries) RevokeAllMerchantApiKeys(ctx context.Context, merchantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllMerchantApiKeys, merchantID)
	return err
}

const setEmailVerificationStatus = `-- name: SetEmailVerificationStatus :one
UPDATE merchants
SET email_verified = $1
WHERE id = $2
RETURNING id, personal_name, password, email, phone_number, business_name, buisness_type, website_url, status, kyb_tier, created_at, updated_at, email_verified
`

type SetEmailVerificationStatusParams struct {
	EmailVerified bool      `json:"email_verified"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) SetEmailVerificationStatus(ctx context.Context, arg SetEmailVerificationStatusParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, setEmailVerificationStatus, arg.EmailVerified, arg.ID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.PersonalName,
		&i.Password,
		&i.Email,
		&i.PhoneNumber,
		&i.BusinessName,
		&i.BuisnessType,
		&i.WebsiteUrl,
		&i.Status,
		&i.KybTier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerified,
	)
	return i, err
}

const updateApiKeyLastUsage = `-- name: UpdateApiKeyLastUsage :exec
UPDATE merchants_api_keys
SET last_used_at = NOW()
WHERE merchant_id = $1
`

func (q *Queries) UpdateApiKeyLastUsage(ctx context.Context, merchantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateApiKeyLastUsage, merchantID)
	return err
}

const updateEmailVerificationCode = `-- name: UpdateEmailVerificationCode :one
UPDATE merchant_email_verification_codes
SET verified = $1
WHERE id = $2
RETURNING id, merchant_id, email, code, expires_at, verified, created_at
`

type UpdateEmailVerificationCodeParams struct {
	Verified pgtype.Bool `json:"verified"`
	ID       uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateEmailVerificationCode(ctx context.Context, arg UpdateEmailVerificationCodeParams) (MerchantEmailVerificationCode, error) {
	row := q.db.QueryRow(ctx, updateEmailVerificationCode, arg.Verified, arg.ID)
	var i MerchantEmailVerificationCode
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const updateMerchantKybTier = `-- name: UpdateMerchantKybTier :one
UPDATE merchants
SET kyb_tier = $1
WHERE id = $2
RETURNING id, personal_name, password, email, phone_number, business_name, buisness_type, website_url, status, kyb_tier, created_at, updated_at, email_verified
`

type UpdateMerchantKybTierParams struct {
	KybTier KybTier   `json:"kyb_tier"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) UpdateMerchantKybTier(ctx context.Context, arg UpdateMerchantKybTierParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantKybTier, arg.KybTier, arg.ID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.PersonalName,
		&i.Password,
		&i.Email,
		&i.PhoneNumber,
		&i.BusinessName,
		&i.BuisnessType,
		&i.WebsiteUrl,
		&i.Status,
		&i.KybTier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerified,
	)
	return i, err
}

const updateMerchantPortalConfig = `-- name: UpdateMerchantPortalConfig :one
UPDATE merchants_portal_config
SET 
    logo_url = COALESCE($1, logo_url),
    primary_color = COALESCE($2, primary_color),
    secondary_color = COALESCE($3, secondary_color),
    support_email = COALESCE($4, support_email),
    return_url = COALESCE($5, return_url),
    smart_retry_enabled = COALESCE($6, smart_retry_enabled),
    updated_at = now()
WHERE merchant_id = $7
RETURNING id, merchant_id, logo_url, primary_color, secondary_color, support_email, return_url, smart_retry_enabled, created_at, updated_at
`

type UpdateMerchantPortalConfigParams struct {
	LogoUrl           *string     `json:"logo_url"`
	PrimaryColor      *string     `json:"primary_color"`
	SecondaryColor    *string     `json:"secondary_color"`
	SupportEmail      *string     `json:"support_email"`
	ReturnUrl         *string     `json:"return_url"`
	SmartRetryEnabled pgtype.Bool `json:"smart_retry_enabled"`
	MerchantID        pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) UpdateMerchantPortalConfig(ctx context.Context, arg UpdateMerchantPortalConfigParams) (MerchantsPortalConfig, error) {
	row := q.db.QueryRow(ctx, updateMerchantPortalConfig,
		arg.LogoUrl,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.SupportEmail,
		arg.ReturnUrl,
		arg.SmartRetryEnabled,
		arg.MerchantID,
	)
	var i MerchantsPortalConfig
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.SupportEmail,
		&i.ReturnUrl,
		&i.SmartRetryEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMerchantSplitConfig = `-- name: UpdateMerchantSplitConfig :one
UPDATE merchants_split_config
SET 
    label = COALESCE($1, label),
    recepient_type = COALESCE($2, recepient_type),
    nomba_account_id = COALESCE($3, nomba_account_id),
    split_type = COALESCE($4, split_type),
    value = COALESCE($5, value),
    active = COALESCE($6, active),
    updated_at = now()
WHERE id = $7 AND merchant_id = $8
RETURNING id, merchant_id, label, recepient_type, nomba_account_id, split_type, value, active, created_at, updated_at
`

type UpdateMerchantSplitConfigParams struct {
	Label          *string     `json:"label"`
	RecepientType  *string     `json:"recepient_type"`
	NombaAccountID *string     `json:"nomba_account_id"`
	SplitType      *string     `json:"split_type"`
	Value          pgtype.Int8 `json:"value"`
	Active         pgtype.Bool `json:"active"`
	ID             uuid.UUID   `json:"id"`
	MerchantID     pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) UpdateMerchantSplitConfig(ctx context.Context, arg UpdateMerchantSplitConfigParams) (MerchantsSplitConfig, error) {
	row := q.db.QueryRow(ctx, updateMerchantSplitConfig,
		arg.Label,
		arg.RecepientType,
		arg.NombaAccountID,
		arg.SplitType,
		arg.Value,
		arg.Active,
		arg.ID,
		arg.MerchantID,
	)
	var i MerchantsSplitConfig
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Label,
		&i.RecepientType,
		&i.NombaAccountID,
		&i.SplitType,
		&i.Value,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMerchantWebhookConfig = `-- name: UpdateMerchantWebhookConfig :one
UPDATE merchants_webhook_urls
SET 
    webhook_url = COALESCE($1, webhook_url),
    webhook_secret = COALESCE($2, webhook_secret),
    updated_at = now()
WHERE merchant_id = $3
RETURNING id, merchant_id, webhook_url, webhook_secret, created_at, updated_at
`

type UpdateMerchantWebhookConfigParams struct {
	WebhookUrl    *string     `json:"webhook_url"`
	WebhookSecret *string     `json:"webhook_secret"`
	MerchantID    pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) UpdateMerchantWebhookConfig(ctx context.Context, arg UpdateMerchantWebhookConfigParams) (MerchantsWebhookUrl, error) {
	row := q.db.QueryRow(ctx, updateMerchantWebhookConfig, arg.WebhookUrl, arg.WebhookSecret, arg.MerchantID)
	var i MerchantsWebhookUrl
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyEmailCodeAtomic = `-- name: VerifyEmailCodeAtomic :one
UPDATE merchant_email_verification_codes
SET verified = true
WHERE email = $1
  AND code = $2
  AND expires_at > NOW()
  AND verified = false
RETURNING id, merchant_id, email, code, expires_at, verified
`

type VerifyEmailCodeAtomicParams struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

type VerifyEmailCodeAtomicRow struct {
	ID         uuid.UUID        `json:"id"`
	MerchantID uuid.UUID        `json:"merchant_id"`
	Email      string           `json:"email"`
	Code       string           `json:"code"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	Verified   pgtype.Bool      `json:"verified"`
}

func (q *Queries) VerifyEmailCodeAtomic(ctx context.Context, arg VerifyEmailCodeAtomicParams) (VerifyEmailCodeAtomicRow, error) {
	row := q.db.QueryRow(ctx, verifyEmailCodeAtomic, arg.Email, arg.Code)
	var i VerifyEmailCodeAtomicRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
		&i.Verified,
	)
	return i, err
}
