// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AttemptStatus string

const (
	AttemptStatusSuccess AttemptStatus = "success"
	AttemptStatusFailed  AttemptStatus = "failed"
	AttemptStatusPending AttemptStatus = "pending"
)

func (e *AttemptStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttemptStatus(s)
	case string:
		*e = AttemptStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AttemptStatus: %T", src)
	}
	return nil
}

type NullAttemptStatus struct {
	AttemptStatus AttemptStatus `json:"attempt_status"`
	Valid         bool          `json:"valid"` // Valid is true if AttemptStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttemptStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AttemptStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttemptStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttemptStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttemptStatus), nil
}

type AttemptType string

const (
	AttemptTypeChargeRetry          AttemptType = "charge_retry"
	AttemptTypeReminderSent         AttemptType = "reminder_sent"
	AttemptTypePaymentMethodRequest AttemptType = "payment_method_request"
	AttemptTypeCancellationWarning  AttemptType = "cancellation_warning"
	AttemptTypeSmartRetryScheduled  AttemptType = "smart_retry_scheduled"
)

func (e *AttemptType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttemptType(s)
	case string:
		*e = AttemptType(s)
	default:
		return fmt.Errorf("unsupported scan type for AttemptType: %T", src)
	}
	return nil
}

type NullAttemptType struct {
	AttemptType AttemptType `json:"attempt_type"`
	Valid       bool        `json:"valid"` // Valid is true if AttemptType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttemptType) Scan(value interface{}) error {
	if value == nil {
		ns.AttemptType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttemptType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttemptType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttemptType), nil
}

type BuisnessType string

const (
	BuisnessTypeSoleProprietorship BuisnessType = "sole_proprietorship"
	BuisnessTypeIndividual         BuisnessType = "individual"
	BuisnessTypeRegisteredbusiness BuisnessType = "registered business"
)

func (e *BuisnessType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BuisnessType(s)
	case string:
		*e = BuisnessType(s)
	default:
		return fmt.Errorf("unsupported scan type for BuisnessType: %T", src)
	}
	return nil
}

type NullBuisnessType struct {
	BuisnessType BuisnessType `json:"buisness_type"`
	Valid        bool         `json:"valid"` // Valid is true if BuisnessType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBuisnessType) Scan(value interface{}) error {
	if value == nil {
		ns.BuisnessType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BuisnessType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBuisnessType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BuisnessType), nil
}

type DeclineType string

const (
	DeclineTypeSoft    DeclineType = "soft"
	DeclineTypeHard    DeclineType = "hard"
	DeclineTypeNetwork DeclineType = "network"
)

func (e *DeclineType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeclineType(s)
	case string:
		*e = DeclineType(s)
	default:
		return fmt.Errorf("unsupported scan type for DeclineType: %T", src)
	}
	return nil
}

type NullDeclineType struct {
	DeclineType DeclineType `json:"decline_type"`
	Valid       bool        `json:"valid"` // Valid is true if DeclineType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeclineType) Scan(value interface{}) error {
	if value == nil {
		ns.DeclineType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeclineType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeclineType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeclineType), nil
}

type DvaStatus string

const (
	DvaStatusActive    DvaStatus = "active"
	DvaStatusSuspended DvaStatus = "suspended"
	DvaStatusClosed    DvaStatus = "closed"
)

func (e *DvaStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DvaStatus(s)
	case string:
		*e = DvaStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DvaStatus: %T", src)
	}
	return nil
}

type NullDvaStatus struct {
	DvaStatus DvaStatus `json:"dva_status"`
	Valid     bool      `json:"valid"` // Valid is true if DvaStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDvaStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DvaStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DvaStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDvaStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DvaStatus), nil
}

type InvoiceStatus string

const (
	InvoiceStatusDraft         InvoiceStatus = "draft"
	InvoiceStatusOpen          InvoiceStatus = "open"
	InvoiceStatusPaid          InvoiceStatus = "paid"
	InvoiceStatusVoid          InvoiceStatus = "void"
	InvoiceStatusUncollectible InvoiceStatus = "uncollectible"
)

func (e *InvoiceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceStatus(s)
	case string:
		*e = InvoiceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceStatus: %T", src)
	}
	return nil
}

type NullInvoiceStatus struct {
	InvoiceStatus InvoiceStatus `json:"invoice_status"`
	Valid         bool          `json:"valid"` // Valid is true if InvoiceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceStatus), nil
}

type InvoiceType string

const (
	InvoiceTypeSubscription    InvoiceType = "subscription"
	InvoiceTypeProration       InvoiceType = "proration"
	InvoiceTypeTrialConversion InvoiceType = "trial_conversion"
	InvoiceTypeTopup           InvoiceType = "topup"
	InvoiceTypeOneOff          InvoiceType = "one_off"
)

func (e *InvoiceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceType(s)
	case string:
		*e = InvoiceType(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceType: %T", src)
	}
	return nil
}

type NullInvoiceType struct {
	InvoiceType InvoiceType `json:"invoice_type"`
	Valid       bool        `json:"valid"` // Valid is true if InvoiceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceType) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceType), nil
}

type KybDocumentType string

const (
	KybDocumentTypeCacCertificate         KybDocumentType = "cac_certificate"
	KybDocumentTypeGovernmentID           KybDocumentType = "government_id"
	KybDocumentTypeSelfie                 KybDocumentType = "selfie"
	KybDocumentTypeProofOfAddress         KybDocumentType = "proof_of_address"
	KybDocumentTypeBuisnessRegCertificate KybDocumentType = "buisness_reg_certificate"
)

func (e *KybDocumentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KybDocumentType(s)
	case string:
		*e = KybDocumentType(s)
	default:
		return fmt.Errorf("unsupported scan type for KybDocumentType: %T", src)
	}
	return nil
}

type NullKybDocumentType struct {
	KybDocumentType KybDocumentType `json:"kyb_document_type"`
	Valid           bool            `json:"valid"` // Valid is true if KybDocumentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKybDocumentType) Scan(value interface{}) error {
	if value == nil {
		ns.KybDocumentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KybDocumentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKybDocumentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KybDocumentType), nil
}

type KybDocumentVerificationStatus string

const (
	KybDocumentVerificationStatusPending  KybDocumentVerificationStatus = "pending"
	KybDocumentVerificationStatusVerified KybDocumentVerificationStatus = "verified"
	KybDocumentVerificationStatusRejected KybDocumentVerificationStatus = "rejected"
)

func (e *KybDocumentVerificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KybDocumentVerificationStatus(s)
	case string:
		*e = KybDocumentVerificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for KybDocumentVerificationStatus: %T", src)
	}
	return nil
}

type NullKybDocumentVerificationStatus struct {
	KybDocumentVerificationStatus KybDocumentVerificationStatus `json:"kyb_document_verification_status"`
	Valid                         bool                          `json:"valid"` // Valid is true if KybDocumentVerificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKybDocumentVerificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.KybDocumentVerificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KybDocumentVerificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKybDocumentVerificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KybDocumentVerificationStatus), nil
}

type KybTier string

const (
	KybTierTier0 KybTier = "tier_0"
	KybTierTier1 KybTier = "tier_1"
	KybTierTier2 KybTier = "tier_2"
	KybTierTier3 KybTier = "tier_3"
)

func (e *KybTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KybTier(s)
	case string:
		*e = KybTier(s)
	default:
		return fmt.Errorf("unsupported scan type for KybTier: %T", src)
	}
	return nil
}

type NullKybTier struct {
	KybTier KybTier `json:"kyb_tier"`
	Valid   bool    `json:"valid"` // Valid is true if KybTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKybTier) Scan(value interface{}) error {
	if value == nil {
		ns.KybTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KybTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKybTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KybTier), nil
}

type MerchantAccountStatus string

const (
	MerchantAccountStatusPending       MerchantAccountStatus = "pending"
	MerchantAccountStatusBasicVerified MerchantAccountStatus = "basic_verified"
	MerchantAccountStatusFullyVerified MerchantAccountStatus = "fully_verified"
	MerchantAccountStatusSuspended     MerchantAccountStatus = "suspended"
	MerchantAccountStatusRejected      MerchantAccountStatus = "rejected"
)

func (e *MerchantAccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MerchantAccountStatus(s)
	case string:
		*e = MerchantAccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MerchantAccountStatus: %T", src)
	}
	return nil
}

type NullMerchantAccountStatus struct {
	MerchantAccountStatus MerchantAccountStatus `json:"merchant_account_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if MerchantAccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMerchantAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MerchantAccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MerchantAccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMerchantAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MerchantAccountStatus), nil
}

type PaymentMethodType string

const (
	PaymentMethodTypeCard PaymentMethodType = "card"
	PaymentMethodTypeDva  PaymentMethodType = "dva"
)

func (e *PaymentMethodType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethodType(s)
	case string:
		*e = PaymentMethodType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethodType: %T", src)
	}
	return nil
}

type NullPaymentMethodType struct {
	PaymentMethodType PaymentMethodType `json:"payment_method_type"`
	Valid             bool              `json:"valid"` // Valid is true if PaymentMethodType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethodType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethodType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethodType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethodType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethodType), nil
}

type PayoutStatus string

const (
	PayoutStatusPending    PayoutStatus = "pending"
	PayoutStatusProcessing PayoutStatus = "processing"
	PayoutStatusCompleted  PayoutStatus = "completed"
	PayoutStatusFailed     PayoutStatus = "failed"
	PayoutStatusReversed   PayoutStatus = "reversed"
)

func (e *PayoutStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PayoutStatus(s)
	case string:
		*e = PayoutStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PayoutStatus: %T", src)
	}
	return nil
}

type NullPayoutStatus struct {
	PayoutStatus PayoutStatus `json:"payout_status"`
	Valid        bool         `json:"valid"` // Valid is true if PayoutStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPayoutStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PayoutStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PayoutStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPayoutStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PayoutStatus), nil
}

type PendingCreditReason string

const (
	PendingCreditReasonReceivedDuringPause       PendingCreditReason = "received_during_pause"
	PendingCreditReasonReceivedAfterCancellation PendingCreditReason = "received_after_cancellation"
	PendingCreditReasonOverpayment               PendingCreditReason = "overpayment"
	PendingCreditReasonAdvancePayment            PendingCreditReason = "advance_payment"
	PendingCreditReasonMisdirected               PendingCreditReason = "misdirected"
)

func (e *PendingCreditReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PendingCreditReason(s)
	case string:
		*e = PendingCreditReason(s)
	default:
		return fmt.Errorf("unsupported scan type for PendingCreditReason: %T", src)
	}
	return nil
}

type NullPendingCreditReason struct {
	PendingCreditReason PendingCreditReason `json:"pending_credit_reason"`
	Valid               bool                `json:"valid"` // Valid is true if PendingCreditReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPendingCreditReason) Scan(value interface{}) error {
	if value == nil {
		ns.PendingCreditReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PendingCreditReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPendingCreditReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PendingCreditReason), nil
}

type PendingCreditStatus string

const (
	PendingCreditStatusPending    PendingCreditStatus = "pending"
	PendingCreditStatusApplied    PendingCreditStatus = "applied"
	PendingCreditStatusRefunded   PendingCreditStatus = "refunded"
	PendingCreditStatusWrittenOff PendingCreditStatus = "written_off"
)

func (e *PendingCreditStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PendingCreditStatus(s)
	case string:
		*e = PendingCreditStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PendingCreditStatus: %T", src)
	}
	return nil
}

type NullPendingCreditStatus struct {
	PendingCreditStatus PendingCreditStatus `json:"pending_credit_status"`
	Valid               bool                `json:"valid"` // Valid is true if PendingCreditStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPendingCreditStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PendingCreditStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PendingCreditStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPendingCreditStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PendingCreditStatus), nil
}

type PlanIntervalUnit string

const (
	PlanIntervalUnitDaily   PlanIntervalUnit = "daily"
	PlanIntervalUnitWeekly  PlanIntervalUnit = "weekly"
	PlanIntervalUnitMonthly PlanIntervalUnit = "monthly"
	PlanIntervalUnitYearly  PlanIntervalUnit = "yearly"
)

func (e *PlanIntervalUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlanIntervalUnit(s)
	case string:
		*e = PlanIntervalUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for PlanIntervalUnit: %T", src)
	}
	return nil
}

type NullPlanIntervalUnit struct {
	PlanIntervalUnit PlanIntervalUnit `json:"plan_interval_unit"`
	Valid            bool             `json:"valid"` // Valid is true if PlanIntervalUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlanIntervalUnit) Scan(value interface{}) error {
	if value == nil {
		ns.PlanIntervalUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlanIntervalUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlanIntervalUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlanIntervalUnit), nil
}

type PlanStatus string

const (
	PlanStatusActive   PlanStatus = "active"
	PlanStatusArchived PlanStatus = "archived"
)

func (e *PlanStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlanStatus(s)
	case string:
		*e = PlanStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PlanStatus: %T", src)
	}
	return nil
}

type NullPlanStatus struct {
	PlanStatus PlanStatus `json:"plan_status"`
	Valid      bool       `json:"valid"` // Valid is true if PlanStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlanStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PlanStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlanStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlanStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlanStatus), nil
}

type PlanType string

const (
	PlanTypeFlat    PlanType = "flat"
	PlanTypePerUnit PlanType = "per_unit"
	PlanTypeMetered PlanType = "metered"
)

func (e *PlanType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlanType(s)
	case string:
		*e = PlanType(s)
	default:
		return fmt.Errorf("unsupported scan type for PlanType: %T", src)
	}
	return nil
}

type NullPlanType struct {
	PlanType PlanType `json:"plan_type"`
	Valid    bool     `json:"valid"` // Valid is true if PlanType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlanType) Scan(value interface{}) error {
	if value == nil {
		ns.PlanType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlanType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlanType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlanType), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusPending   SubscriptionStatus = "pending"
	SubscriptionStatusTrialing  SubscriptionStatus = "trialing"
	SubscriptionStatusActive    SubscriptionStatus = "active"
	SubscriptionStatusPastDue   SubscriptionStatus = "past_due"
	SubscriptionStatusCancelled SubscriptionStatus = "cancelled"
	SubscriptionStatusPaused    SubscriptionStatus = "paused"
	SubscriptionStatusExpired   SubscriptionStatus = "expired"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus `json:"subscription_status"`
	Valid              bool               `json:"valid"` // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type TransactionStatus string

const (
	TransactionStatusSuccess  TransactionStatus = "success"
	TransactionStatusFailed   TransactionStatus = "failed"
	TransactionStatusPending  TransactionStatus = "pending"
	TransactionStatusReversed TransactionStatus = "reversed"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus `json:"transaction_status"`
	Valid             bool              `json:"valid"` // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

type TransactionType string

const (
	TransactionTypeCardCharge  TransactionType = "card_charge"
	TransactionTypeDvaTransfer TransactionType = "dva_transfer"
	TransactionTypeWalletDebit TransactionType = "wallet_debit"
	TransactionTypeWalletTopup TransactionType = "wallet_topup"
	TransactionTypeRefund      TransactionType = "refund"
	TransactionTypePayout      TransactionType = "payout"
	TransactionTypePlatformFee TransactionType = "platform_fee"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type WebhookStatus string

const (
	WebhookStatusPending   WebhookStatus = "pending"
	WebhookStatusDelivered WebhookStatus = "delivered"
	WebhookStatusFailed    WebhookStatus = "failed"
	WebhookStatusExhausted WebhookStatus = "exhausted"
)

func (e *WebhookStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookStatus(s)
	case string:
		*e = WebhookStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookStatus: %T", src)
	}
	return nil
}

type NullWebhookStatus struct {
	WebhookStatus WebhookStatus `json:"webhook_status"`
	Valid         bool          `json:"valid"` // Valid is true if WebhookStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookStatus), nil
}

type CustomerWallet struct {
	ID                  uuid.UUID          `json:"id"`
	MerchantID          uuid.UUID          `json:"merchant_id"`
	CustomerID          string             `json:"customer_id"`
	SubscriptionID      uuid.UUID          `json:"subscription_id"`
	Balance             int64              `json:"balance"`
	LowBalanceThreshold int64              `json:"low_balance_threshold"`
	Currency            string             `json:"currency"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type DedicatedVirtualAccount struct {
	ID                uuid.UUID          `json:"id"`
	MerchantID        uuid.UUID          `json:"merchant_id"`
	SubscriptionID    uuid.UUID          `json:"subscription_id"`
	CustomerID        string             `json:"customer_id"`
	CustomerName      string             `json:"customer_name"`
	AccountRef        string             `json:"account_ref"`
	NombaAccountID    *string            `json:"nomba_account_id"`
	BankAccountNumber string             `json:"bank_account_number"`
	BankAccountName   string             `json:"bank_account_name"`
	BankName          string             `json:"bank_name"`
	BvnHash           *string            `json:"bvn_hash"`
	Status            DvaStatus          `json:"status"`
	SuspendedAt       pgtype.Timestamptz `json:"suspended_at"`
	ClosedAt          pgtype.Timestamptz `json:"closed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type DunningAttempt struct {
	ID               uuid.UUID          `json:"id"`
	SubscriptionID   uuid.UUID          `json:"subscription_id"`
	InvoiceID        uuid.UUID          `json:"invoice_id"`
	AttemptNumber    int32              `json:"attempt_number"`
	AttemptType      AttemptType        `json:"attempt_type"`
	Status           AttemptStatus      `json:"status"`
	FailureCode      *string            `json:"failure_code"`
	DeclineType      *string            `json:"decline_type"`
	AttemptedAt      pgtype.Timestamptz `json:"attempted_at"`
	NextAttemptAt    pgtype.Timestamptz `json:"next_attempt_at"`
	SmartRetry       bool               `json:"smart_retry"`
	NotificationSent pgtype.Bool        `json:"notification_sent"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Invoice struct {
	ID                uuid.UUID          `json:"id"`
	MerchantID        uuid.UUID          `json:"merchant_id"`
	SubscriptionID    uuid.UUID          `json:"subscription_id"`
	CustomerID        string             `json:"customer_id"`
	InvoiceType       InvoiceType        `json:"invoice_type"`
	Total             int64              `json:"total"`
	AmountPaid        int64              `json:"amount_paid"`
	Currency          string             `json:"currency"`
	PeriodStart       pgtype.Timestamptz `json:"period_start"`
	PeriodEnd         pgtype.Timestamptz `json:"period_end"`
	Status            InvoiceStatus      `json:"status"`
	PaymentMethodType *string            `json:"payment_method_type"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
	DueDate           pgtype.Timestamptz `json:"due_date"`
	NombaOrderRef     *string            `json:"nomba_order_ref"`
	NombaTxnRef       *string            `json:"nomba_txn_ref"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type InvoiceLineItem struct {
	ID          uuid.UUID          `json:"id"`
	InvoiceID   uuid.UUID          `json:"invoice_id"`
	Description string             `json:"description"`
	Quantity    int32              `json:"quantity"`
	UnitAmount  int64              `json:"unit_amount"`
	Total       int64              `json:"total"`
	Type        string             `json:"type"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Merchant struct {
	ID            uuid.UUID             `json:"id"`
	PersonalName  string                `json:"personal_name"`
	Password      string                `json:"password"`
	Email         string                `json:"email"`
	PhoneNumber   *string               `json:"phone_number"`
	BusinessName  *string               `json:"business_name"`
	BuisnessType  NullBuisnessType      `json:"buisness_type"`
	WebsiteUrl    *string               `json:"website_url"`
	Status        MerchantAccountStatus `json:"status"`
	KybTier       KybTier               `json:"kyb_tier"`
	CreatedAt     pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz    `json:"updated_at"`
	EmailVerified bool                  `json:"email_verified"`
}

type MerchantEmailVerificationCode struct {
	ID         uuid.UUID        `json:"id"`
	MerchantID uuid.UUID        `json:"merchant_id"`
	Email      string           `json:"email"`
	Code       string           `json:"code"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	Verified   pgtype.Bool      `json:"verified"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type MerchantsApiKey struct {
	ID          uuid.UUID          `json:"id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	KeyHash     string             `json:"key_hash"`
	KeyPrefix   string             `json:"key_prefix"`
	Environment string             `json:"environment"`
	Label       *string            `json:"label"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	Revoked     bool               `json:"revoked"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MerchantsBalance struct {
	ID               uuid.UUID          `json:"id"`
	MerchantID       pgtype.UUID        `json:"merchant_id"`
	AvailableBalance int64              `json:"available_balance"`
	PendingBalance   int64              `json:"pending_balance"`
	LastUpdatedAt    pgtype.Timestamptz `json:"last_updated_at"`
}

type MerchantsKybDetail struct {
	ID              uuid.UUID          `json:"id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	BvnHash         *string            `json:"bvn_hash"`
	NinHash         *string            `json:"nin_hash"`
	CacRegNumber    *string            `json:"cac_reg_number"`
	BuisnessRegName *string            `json:"buisness_reg_name"`
	KybSubmittedAt  pgtype.Timestamptz `json:"kyb_submitted_at"`
	KybVerifiedAt   pgtype.Timestamptz `json:"kyb_verified_at"`
	RejectionReason *string            `json:"rejection_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type MerchantsKycDocument struct {
	ID              uuid.UUID                     `json:"id"`
	MerchantID      pgtype.UUID                   `json:"merchant_id"`
	DocumentType    KybDocumentType               `json:"document_type"`
	DocumentUrl     string                        `json:"document_url"`
	DocumentHash    string                        `json:"document_hash"`
	Status          KybDocumentVerificationStatus `json:"status"`
	VerifiedAt      pgtype.Timestamptz            `json:"verified_at"`
	RejectionReason *string                       `json:"rejection_reason"`
	CreatedAt       pgtype.Timestamptz            `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz            `json:"updated_at"`
}

type MerchantsPortalConfig struct {
	ID                uuid.UUID          `json:"id"`
	MerchantID        pgtype.UUID        `json:"merchant_id"`
	LogoUrl           *string            `json:"logo_url"`
	PrimaryColor      *string            `json:"primary_color"`
	SecondaryColor    *string            `json:"secondary_color"`
	SupportEmail      *string            `json:"support_email"`
	ReturnUrl         *string            `json:"return_url"`
	SmartRetryEnabled pgtype.Bool        `json:"smart_retry_enabled"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type MerchantsSettlementAccount struct {
	ID            uuid.UUID          `json:"id"`
	MerchantID    pgtype.UUID        `json:"merchant_id"`
	BankName      string             `json:"bank_name"`
	AccountNumber string             `json:"account_number"`
	AccountName   string             `json:"account_name"`
	BankCode      string             `json:"bank_code"`
	Verified      bool               `json:"verified"`
	VerifiedAt    pgtype.Timestamptz `json:"verified_at"`
	IsPrimary     bool               `json:"is_primary"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type MerchantsSplitConfig struct {
	ID             uuid.UUID          `json:"id"`
	MerchantID     pgtype.UUID        `json:"merchant_id"`
	Label          string             `json:"label"`
	RecepientType  string             `json:"recepient_type"`
	NombaAccountID *string            `json:"nomba_account_id"`
	SplitType      string             `json:"split_type"`
	Value          int64              `json:"value"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type MerchantsWebhookUrl struct {
	ID            uuid.UUID          `json:"id"`
	MerchantID    pgtype.UUID        `json:"merchant_id"`
	WebhookUrl    string             `json:"webhook_url"`
	WebhookSecret string             `json:"webhook_secret"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Payout struct {
	ID                     uuid.UUID          `json:"id"`
	MerchantID             uuid.UUID          `json:"merchant_id"`
	SettlementAccountID    uuid.UUID          `json:"settlement_account_id"`
	Amount                 int64              `json:"amount"`
	Currency               string             `json:"currency"`
	Fee                    int64              `json:"fee"`
	NetAmount              int64              `json:"net_amount"`
	Status                 PayoutStatus       `json:"status"`
	NombaTransferReference string             `json:"nomba_transfer_reference"`
	InitiatedAt            pgtype.Timestamptz `json:"initiated_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	FailureReason          *string            `json:"failure_reason"`
}

type PendingCredit struct {
	ID               uuid.UUID           `json:"id"`
	MerchantID       uuid.UUID           `json:"merchant_id"`
	SubscriptionID   uuid.UUID           `json:"subscription_id"`
	DvaID            uuid.UUID           `json:"dva_id"`
	Amount           int64               `json:"amount"`
	Currency         string              `json:"currency"`
	Reason           PendingCreditReason `json:"reason"`
	NombaTxnID       string              `json:"nomba_txn_id"`
	SenderBank       *string             `json:"sender_bank"`
	ReceivedAt       pgtype.Timestamptz  `json:"received_at"`
	Status           PendingCreditStatus `json:"status"`
	ResolvedAt       pgtype.Timestamptz  `json:"resolved_at"`
	ResolvedBy       *string             `json:"resolved_by"`
	AppliedToInvoice pgtype.UUID         `json:"applied_to_invoice"`
	CreatedAt        pgtype.Timestamptz  `json:"created_at"`
}

type Plan struct {
	ID            uuid.UUID          `json:"id"`
	MerchantID    uuid.UUID          `json:"merchant_id"`
	Name          string             `json:"name"`
	Description   *string            `json:"description"`
	PlanType      PlanType           `json:"plan_type"`
	Amount        int64              `json:"amount"`
	Currency      string             `json:"currency"`
	UnitName      *string            `json:"unit_name"`
	MaxUnits      pgtype.Int4        `json:"max_units"`
	IntervalUnit  PlanIntervalUnit   `json:"interval_unit"`
	TrialDays     int32              `json:"trial_days"`
	Status        PlanStatus         `json:"status"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	IntervalCount int32              `json:"interval_count"`
}

type PlanTier struct {
	ID        uuid.UUID          `json:"id"`
	PlanID    uuid.UUID          `json:"plan_id"`
	UpTo      pgtype.Int4        `json:"up_to"`
	UnitPrice int64              `json:"unit_price"`
	FlatFee   int64              `json:"flat_fee"`
	TierOrder int32              `json:"tier_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PortalSession struct {
	ID         uuid.UUID          `json:"id"`
	MerchantID uuid.UUID          `json:"merchant_id"`
	CustomerID string             `json:"customer_id"`
	TokenHash  string             `json:"token_hash"`
	ReturnUrl  *string            `json:"return_url"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Used       bool               `json:"used"`
	UsedAt     pgtype.Timestamptz `json:"used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ProcessedWebhookEvent struct {
	ID           uuid.UUID          `json:"id"`
	EventSource  string             `json:"event_source"`
	EventID      string             `json:"event_id"`
	EventType    string             `json:"event_type"`
	Payload      []byte             `json:"payload"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	ProcessingMs pgtype.Int4        `json:"processing_ms"`
}

type Subscription struct {
	ID                 uuid.UUID          `json:"id"`
	MerchantID         uuid.UUID          `json:"merchant_id"`
	CustomerID         string             `json:"customer_id"`
	CustomerEmail      string             `json:"customer_email"`
	CustomerName       string             `json:"customer_name"`
	PlanID             uuid.UUID          `json:"plan_id"`
	Status             SubscriptionStatus `json:"status"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	TrialEndsAt        pgtype.Timestamptz `json:"trial_ends_at"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CancelAtPeriodEnd  pgtype.Bool        `json:"cancel_at_period_end"`
	CancellationReason *string            `json:"cancellation_reason"`
	PausedAt           pgtype.Timestamptz `json:"paused_at"`
	PauseResumesAt     pgtype.Timestamptz `json:"pause_resumes_at"`
	PauseReason        *string            `json:"pause_reason"`
	PaymentMethodType  PaymentMethodType  `json:"payment_method_type"`
	NombaTokenKey      *string            `json:"nomba_token_key"`
	DvaID              pgtype.UUID        `json:"dva_id"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type SubscriptionsEvent struct {
	ID             uuid.UUID          `json:"id"`
	SubscriptionID uuid.UUID          `json:"subscription_id"`
	MerchantID     uuid.UUID          `json:"merchant_id"`
	EventType      string             `json:"event_type"`
	FromState      []byte             `json:"from_state"`
	ToState        []byte             `json:"to_state"`
	Actor          string             `json:"actor"`
	ActorID        *string            `json:"actor_id"`
	Reason         *string            `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SubscriptionsHealth struct {
	SubscriptionID uuid.UUID          `json:"subscription_id"`
	HealthScore    int32              `json:"health_score"`
	Signals        []byte             `json:"signals"`
	LastComputedAt pgtype.Timestamptz `json:"last_computed_at"`
}

type Transaction struct {
	ID              uuid.UUID          `json:"id"`
	MerchantID      uuid.UUID          `json:"merchant_id"`
	SubscriptionID  pgtype.UUID        `json:"subscription_id"`
	InvoiceID       pgtype.UUID        `json:"invoice_id"`
	CustomerID      string             `json:"customer_id"`
	Direction       string             `json:"direction"`
	TransactionType TransactionType    `json:"transaction_type"`
	Status          TransactionStatus  `json:"status"`
	NombaTxnID      *string            `json:"nomba_txn_id"`
	NombaOrderRef   *string            `json:"nomba_order_ref"`
	FailureCode     *string            `json:"failure_code"`
	FailureMessage  *string            `json:"failure_message"`
	DeclineType     NullDeclineType    `json:"decline_type"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type UsageEvent struct {
	ID             uuid.UUID          `json:"id"`
	MerchantID     uuid.UUID          `json:"merchant_id"`
	CustomerID     string             `json:"customer_id"`
	SubscriptionID uuid.UUID          `json:"subscription_id"`
	WalletID       uuid.UUID          `json:"wallet_id"`
	EventType      string             `json:"event_type"`
	Units          pgtype.Numeric     `json:"units"`
	UnitPrice      int64              `json:"unit_price"`
	IdemotencyKey  string             `json:"idemotency_key"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
}

type WebhookDelivery struct {
	ID             uuid.UUID          `json:"id"`
	MerchantID     uuid.UUID          `json:"merchant_id"`
	SubscriptionID uuid.UUID          `json:"subscription_id"`
	EventType      string             `json:"event_type"`
	Payload        []byte             `json:"payload"`
	IdempotencyKey string             `json:"idempotency_key"`
	WebhookUrl     string             `json:"webhook_url"`
	Status         WebhookStatus      `json:"status"`
	AttemptCount   int32              `json:"attempt_count"`
	MaxAttempts    int32              `json:"max_attempts"`
	NextRetryAt    pgtype.Timestamptz `json:"next_retry_at"`
	LastAttemptAt  pgtype.Timestamptz `json:"last_attempt_at"`
	LastHttpStatus pgtype.Int4        `json:"last_http_status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
}
