// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_credits.queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingCredit = `-- name: CreatePendingCredit :one
INSERT INTO pending_credits (
    merchant_id,
    subscription_id,
    dva_id,
    amount,
    currency,
    reason,
    nomba_txn_id,
    sender_bank,
    received_at,
    status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'pending')
RETURNING id, merchant_id, subscription_id, dva_id, amount, currency, reason, nomba_txn_id, sender_bank, received_at, status, resolved_at, resolved_by, applied_to_invoice, created_at
`

type CreatePendingCreditParams struct {
	MerchantID     uuid.UUID           `json:"merchant_id"`
	SubscriptionID uuid.UUID           `json:"subscription_id"`
	DvaID          uuid.UUID           `json:"dva_id"`
	Amount         int64               `json:"amount"`
	Currency       string              `json:"currency"`
	Reason         PendingCreditReason `json:"reason"`
	NombaTxnID     string              `json:"nomba_txn_id"`
	SenderBank     *string             `json:"sender_bank"`
	ReceivedAt     pgtype.Timestamptz  `json:"received_at"`
}

func (q *Queries) CreatePendingCredit(ctx context.Context, arg CreatePendingCreditParams) (PendingCredit, error) {
	row := q.db.QueryRow(ctx, createPendingCredit,
		arg.MerchantID,
		arg.SubscriptionID,
		arg.DvaID,
		arg.Amount,
		arg.Currency,
		arg.Reason,
		arg.NombaTxnID,
		arg.SenderBank,
		arg.ReceivedAt,
	)
	var i PendingCredit
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.SubscriptionID,
		&i.DvaID,
		&i.Amount,
		&i.Currency,
		&i.Reason,
		&i.NombaTxnID,
		&i.SenderBank,
		&i.ReceivedAt,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.AppliedToInvoice,
		&i.CreatedAt,
	)
	return i, err
}
