// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archivePlan = `-- name: ArchivePlan :one
UPDATE plans
SET status = 'archived', updated_at = NOW()
WHERE id = $1 AND merchant_id = $2
RETURNING id, merchant_id, name, description, plan_type, amount, currency, unit_name, max_units, interval_unit, trial_days, status, metadata, created_at, updated_at, interval_count
`

type ArchivePlanParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) ArchivePlan(ctx context.Context, arg ArchivePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, archivePlan, arg.ID, arg.MerchantID)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Description,
		&i.PlanType,
		&i.Amount,
		&i.Currency,
		&i.UnitName,
		&i.MaxUnits,
		&i.IntervalUnit,
		&i.TrialDays,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IntervalCount,
	)
	return i, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (merchant_id,name,description,plan_type,amount,currency,unit_name,max_units,interval_unit,interval_count,trial_days,status,metadata)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
RETURNING id, merchant_id, name, description, plan_type, amount, currency, unit_name, max_units, interval_unit, trial_days, status, metadata, created_at, updated_at, interval_count
`

type CreatePlanParams struct {
	MerchantID    uuid.UUID        `json:"merchant_id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	PlanType      PlanType         `json:"plan_type"`
	Amount        int64            `json:"amount"`
	Currency      string           `json:"currency"`
	UnitName      *string          `json:"unit_name"`
	MaxUnits      pgtype.Int4      `json:"max_units"`
	IntervalUnit  PlanIntervalUnit `json:"interval_unit"`
	IntervalCount int32            `json:"interval_count"`
	TrialDays     int32            `json:"trial_days"`
	Status        PlanStatus       `json:"status"`
	Metadata      []byte           `json:"metadata"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.MerchantID,
		arg.Name,
		arg.Description,
		arg.PlanType,
		arg.Amount,
		arg.Currency,
		arg.UnitName,
		arg.MaxUnits,
		arg.IntervalUnit,
		arg.IntervalCount,
		arg.TrialDays,
		arg.Status,
		arg.Metadata,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Description,
		&i.PlanType,
		&i.Amount,
		&i.Currency,
		&i.UnitName,
		&i.MaxUnits,
		&i.IntervalUnit,
		&i.TrialDays,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IntervalCount,
	)
	return i, err
}

const createPlanTier = `-- name: CreatePlanTier :one
INSERT INTO plan_tiers (plan_id, up_to, unit_price, flat_fee, tier_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, plan_id, up_to, unit_price, flat_fee, tier_order, created_at
`

type CreatePlanTierParams struct {
	PlanID    uuid.UUID   `json:"plan_id"`
	UpTo      pgtype.Int4 `json:"up_to"`
	UnitPrice int64       `json:"unit_price"`
	FlatFee   int64       `json:"flat_fee"`
	TierOrder int32       `json:"tier_order"`
}

func (q *Queries) CreatePlanTier(ctx context.Context, arg CreatePlanTierParams) (PlanTier, error) {
	row := q.db.QueryRow(ctx, createPlanTier,
		arg.PlanID,
		arg.UpTo,
		arg.UnitPrice,
		arg.FlatFee,
		arg.TierOrder,
	)
	var i PlanTier
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.UpTo,
		&i.UnitPrice,
		&i.FlatFee,
		&i.TierOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanByIDAndMerchant = `-- name: GetPlanByIDAndMerchant :one
SELECT id, merchant_id, name, description, plan_type, amount, currency, unit_name, max_units, interval_unit, trial_days, status, metadata, created_at, updated_at, interval_count FROM plans WHERE id = $1 AND merchant_id = $2 LIMIT 1
`

type GetPlanByIDAndMerchantParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) GetPlanByIDAndMerchant(ctx context.Context, arg GetPlanByIDAndMerchantParams) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByIDAndMerchant, arg.ID, arg.MerchantID)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Description,
		&i.PlanType,
		&i.Amount,
		&i.Currency,
		&i.UnitName,
		&i.MaxUnits,
		&i.IntervalUnit,
		&i.TrialDays,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IntervalCount,
	)
	return i, err
}

const getPlanTiers = `-- name: GetPlanTiers :many
SELECT id, plan_id, up_to, unit_price, flat_fee, tier_order, created_at FROM plan_tiers WHERE plan_id = $1 ORDER BY tier_order ASC
`

func (q *Queries) GetPlanTiers(ctx context.Context, planID uuid.UUID) ([]PlanTier, error) {
	rows, err := q.db.Query(ctx, getPlanTiers, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanTier{}
	for rows.Next() {
		var i PlanTier
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.UpTo,
			&i.UnitPrice,
			&i.FlatFee,
			&i.TierOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT id, merchant_id, name, description, plan_type, amount, currency, unit_name, max_units, interval_unit, trial_days, status, metadata, created_at, updated_at, interval_count FROM plans 
WHERE merchant_id = $1
AND ($2::text IS NULL OR status = $2::text)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListPlansParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Column2    string    `json:"column_2"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListPlans(ctx context.Context, arg ListPlansParams) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans,
		arg.MerchantID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Description,
			&i.PlanType,
			&i.Amount,
			&i.Currency,
			&i.UnitName,
			&i.MaxUnits,
			&i.IntervalUnit,
			&i.TrialDays,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IntervalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicPlans = `-- name: ListPublicPlans :many
SELECT id, merchant_id, name, description, plan_type, amount, currency, unit_name, max_units, interval_unit, trial_days, status, metadata, created_at, updated_at, interval_count FROM plans 
WHERE merchant_id = $1 
AND status = 'active'
ORDER BY amount ASC
`

func (q *Queries) ListPublicPlans(ctx context.Context, merchantID uuid.UUID) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPublicPlans, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Description,
			&i.PlanType,
			&i.Amount,
			&i.Currency,
			&i.UnitName,
			&i.MaxUnits,
			&i.IntervalUnit,
			&i.TrialDays,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IntervalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    amount = COALESCE($3, amount),
    currency = COALESCE($4, currency),
    unit_name = COALESCE($5, unit_name),
    max_units = COALESCE($6, max_units),
    interval_unit = COALESCE($7, interval_unit),
    interval_count = COALESCE($8, interval_count),
    trial_days = COALESCE($9, trial_days),
    status = COALESCE($10, status),
    metadata = COALESCE($11, metadata),
    updated_at = NOW()
WHERE id = $12 AND merchant_id = $13
RETURNING id, merchant_id, name, description, plan_type, amount, currency, unit_name, max_units, interval_unit, trial_days, status, metadata, created_at, updated_at, interval_count
`

type UpdatePlanParams struct {
	Name          *string              `json:"name"`
	Description   *string              `json:"description"`
	Amount        pgtype.Int8          `json:"amount"`
	Currency      *string              `json:"currency"`
	UnitName      *string              `json:"unit_name"`
	MaxUnits      pgtype.Int4          `json:"max_units"`
	IntervalUnit  NullPlanIntervalUnit `json:"interval_unit"`
	IntervalCount pgtype.Int4          `json:"interval_count"`
	TrialDays     pgtype.Int4          `json:"trial_days"`
	Status        NullPlanStatus       `json:"status"`
	Metadata      []byte               `json:"metadata"`
	ID            uuid.UUID            `json:"id"`
	MerchantID    uuid.UUID            `json:"merchant_id"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.Name,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.UnitName,
		arg.MaxUnits,
		arg.IntervalUnit,
		arg.IntervalCount,
		arg.TrialDays,
		arg.Status,
		arg.Metadata,
		arg.ID,
		arg.MerchantID,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Description,
		&i.PlanType,
		&i.Amount,
		&i.Currency,
		&i.UnitName,
		&i.MaxUnits,
		&i.IntervalUnit,
		&i.TrialDays,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IntervalCount,
	)
	return i, err
}
