// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchivePlan(ctx context.Context, arg ArchivePlanParams) (Plan, error)
	CancelSubscriptionImmediately(ctx context.Context, arg CancelSubscriptionImmediatelyParams) (Subscription, error)
	CloseDVA(ctx context.Context, arg CloseDVAParams) error
	CompleteMerchantProfileOnboarding(ctx context.Context, arg CompleteMerchantProfileOnboardingParams) (Merchant, error)
	CreateDVA(ctx context.Context, arg CreateDVAParams) (DedicatedVirtualAccount, error)
	CreateEmailVerificationCode(ctx context.Context, arg CreateEmailVerificationCodeParams) (MerchantEmailVerificationCode, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateMerchantApiKeys(ctx context.Context, arg CreateMerchantApiKeysParams) (MerchantsApiKey, error)
	CreateMerchantPortalConfig(ctx context.Context, arg CreateMerchantPortalConfigParams) (MerchantsPortalConfig, error)
	CreateMerchantSplitConfig(ctx context.Context, arg CreateMerchantSplitConfigParams) (MerchantsSplitConfig, error)
	CreateMerchantWebhookConfig(ctx context.Context, arg CreateMerchantWebhookConfigParams) (MerchantsWebhookUrl, error)
	CreateNewMerchant(ctx context.Context, arg CreateNewMerchantParams) (Merchant, error)
	CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error)
	CreatePlanTier(ctx context.Context, arg CreatePlanTierParams) (PlanTier, error)
	CreateSettlementAccount(ctx context.Context, arg CreateSettlementAccountParams) (MerchantsSettlementAccount, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateSubscriptionEventsTimeline(ctx context.Context, arg CreateSubscriptionEventsTimelineParams) error
	DeleteMerchantSplitConfig(ctx context.Context, arg DeleteMerchantSplitConfigParams) (MerchantsSplitConfig, error)
	GetActiveMerchantKeys(ctx context.Context, merchantID pgtype.UUID) (MerchantsApiKey, error)
	GetAllSubscriptionsForMerchant(ctx context.Context, arg GetAllSubscriptionsForMerchantParams) ([]Subscription, error)
	GetEmailVerificationCode(ctx context.Context, arg GetEmailVerificationCodeParams) (MerchantEmailVerificationCode, error)
	GetEmailVerificationStatus(ctx context.Context, id uuid.UUID) (bool, error)
	GetMerchantApiKey(ctx context.Context, keyHash string) (MerchantsApiKey, error)
	GetMerchantByEmail(ctx context.Context, email string) (Merchant, error)
	GetMerchantById(ctx context.Context, id uuid.UUID) (Merchant, error)
	GetMerchantKybTier(ctx context.Context, id uuid.UUID) (KybTier, error)
	GetMerchantPortalConfig(ctx context.Context, merchantID pgtype.UUID) (MerchantsPortalConfig, error)
	GetMerchantSettlementAccounts(ctx context.Context, merchantID pgtype.UUID) ([]MerchantsSettlementAccount, error)
	GetMerchantSplitConfigById(ctx context.Context, arg GetMerchantSplitConfigByIdParams) (MerchantsSplitConfig, error)
	GetMerchantSplitConfigs(ctx context.Context, merchantID pgtype.UUID) ([]MerchantsSplitConfig, error)
	GetMerchantWebhookConfig(ctx context.Context, merchantID pgtype.UUID) (MerchantsWebhookUrl, error)
	GetPlanByIDAndMerchant(ctx context.Context, arg GetPlanByIDAndMerchantParams) (Plan, error)
	GetPlanTiers(ctx context.Context, planID uuid.UUID) ([]PlanTier, error)
	GetSubscriptionForMerchantAndCustomer(ctx context.Context, arg GetSubscriptionForMerchantAndCustomerParams) (Subscription, error)
	ListPlans(ctx context.Context, arg ListPlansParams) ([]Plan, error)
	ListPublicPlans(ctx context.Context, merchantID uuid.UUID) ([]Plan, error)
	RevokeAllMerchantApiKeys(ctx context.Context, merchantID pgtype.UUID) error
	SetEmailVerificationStatus(ctx context.Context, arg SetEmailVerificationStatusParams) (Merchant, error)
	SetSubscriptionStatus(ctx context.Context, arg SetSubscriptionStatusParams) error
	StoreDvaDetails(ctx context.Context, arg StoreDvaDetailsParams) (Subscription, error)
	StoreTokenKey(ctx context.Context, arg StoreTokenKeyParams) (Subscription, error)
	UpdateApiKeyLastUsage(ctx context.Context, merchantID pgtype.UUID) error
	UpdateDVAStatus(ctx context.Context, arg UpdateDVAStatusParams) error
	UpdateEmailVerificationCode(ctx context.Context, arg UpdateEmailVerificationCodeParams) (MerchantEmailVerificationCode, error)
	UpdateInvoiceOrderRef(ctx context.Context, arg UpdateInvoiceOrderRefParams) error
	UpdateInvoicePaymentStatus(ctx context.Context, arg UpdateInvoicePaymentStatusParams) (Invoice, error)
	UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error)
	UpdateMerchantKybTier(ctx context.Context, arg UpdateMerchantKybTierParams) (Merchant, error)
	UpdateMerchantPortalConfig(ctx context.Context, arg UpdateMerchantPortalConfigParams) (MerchantsPortalConfig, error)
	UpdateMerchantSplitConfig(ctx context.Context, arg UpdateMerchantSplitConfigParams) (MerchantsSplitConfig, error)
	UpdateMerchantWebhookConfig(ctx context.Context, arg UpdateMerchantWebhookConfigParams) (MerchantsWebhookUrl, error)
	UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error)
	UpdateSubscriptionDvaId(ctx context.Context, arg UpdateSubscriptionDvaIdParams) error
	VerifyEmailCodeAtomic(ctx context.Context, arg VerifyEmailCodeAtomicParams) (VerifyEmailCodeAtomicRow, error)
}

var _ Querier = (*Queries)(nil)
