// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSubscriptionImmediately = `-- name: CancelSubscriptionImmediately :one
UPDATE subscriptions
SET
    cancelled_at = NOW(),
    cancellation_reason = $1
WHERE merchant_id = $2 AND customer_id = $3
RETURNING id, merchant_id, customer_id, customer_email, customer_name, plan_id, status, current_period_start, current_period_end, trial_ends_at, cancelled_at, cancel_at_period_end, cancellation_reason, paused_at, pause_resumes_at, pause_reason, payment_method_type, nomba_token_key, dva_id, metadata, created_at, updated_at
`

type CancelSubscriptionImmediatelyParams struct {
	CancellationReason *string   `json:"cancellation_reason"`
	MerchantID         uuid.UUID `json:"merchant_id"`
	CustomerID         string    `json:"customer_id"`
}

func (q *Queries) CancelSubscriptionImmediately(ctx context.Context, arg CancelSubscriptionImmediatelyParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, cancelSubscriptionImmediately, arg.CancellationReason, arg.MerchantID, arg.CustomerID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEndsAt,
		&i.CancelledAt,
		&i.CancelAtPeriodEnd,
		&i.CancellationReason,
		&i.PausedAt,
		&i.PauseResumesAt,
		&i.PauseReason,
		&i.PaymentMethodType,
		&i.NombaTokenKey,
		&i.DvaID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (merchant_id,customer_id,customer_email,customer_name,trial_ends_at,plan_id,payment_method_type,status,metadata)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, merchant_id, customer_id, customer_email, customer_name, plan_id, status, current_period_start, current_period_end, trial_ends_at, cancelled_at, cancel_at_period_end, cancellation_reason, paused_at, pause_resumes_at, pause_reason, payment_method_type, nomba_token_key, dva_id, metadata, created_at, updated_at
`

type CreateSubscriptionParams struct {
	MerchantID        uuid.UUID          `json:"merchant_id"`
	CustomerID        string             `json:"customer_id"`
	CustomerEmail     string             `json:"customer_email"`
	CustomerName      string             `json:"customer_name"`
	TrialEndsAt       pgtype.Timestamptz `json:"trial_ends_at"`
	PlanID            uuid.UUID          `json:"plan_id"`
	PaymentMethodType PaymentMethodType  `json:"payment_method_type"`
	Status            SubscriptionStatus `json:"status"`
	Metadata          []byte             `json:"metadata"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.MerchantID,
		arg.CustomerID,
		arg.CustomerEmail,
		arg.CustomerName,
		arg.TrialEndsAt,
		arg.PlanID,
		arg.PaymentMethodType,
		arg.Status,
		arg.Metadata,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEndsAt,
		&i.CancelledAt,
		&i.CancelAtPeriodEnd,
		&i.CancellationReason,
		&i.PausedAt,
		&i.PauseResumesAt,
		&i.PauseReason,
		&i.PaymentMethodType,
		&i.NombaTokenKey,
		&i.DvaID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscriptionEventsTimeline = `-- name: CreateSubscriptionEventsTimeline :exec
INSERT INTO subscriptions_events (subscription_id,merchant_id,event_type,from_state,to_state,actor,actor_id,reason)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
`

type CreateSubscriptionEventsTimelineParams struct {
	SubscriptionID uuid.UUID `json:"subscription_id"`
	MerchantID     uuid.UUID `json:"merchant_id"`
	EventType      string    `json:"event_type"`
	FromState      []byte    `json:"from_state"`
	ToState        []byte    `json:"to_state"`
	Actor          string    `json:"actor"`
	ActorID        *string   `json:"actor_id"`
	Reason         *string   `json:"reason"`
}

func (q *Queries) CreateSubscriptionEventsTimeline(ctx context.Context, arg CreateSubscriptionEventsTimelineParams) error {
	_, err := q.db.Exec(ctx, createSubscriptionEventsTimeline,
		arg.SubscriptionID,
		arg.MerchantID,
		arg.EventType,
		arg.FromState,
		arg.ToState,
		arg.Actor,
		arg.ActorID,
		arg.Reason,
	)
	return err
}

const getAllSubscriptionsForMerchant = `-- name: GetAllSubscriptionsForMerchant :many
SELECT id, merchant_id, customer_id, customer_email, customer_name, plan_id, status, current_period_start, current_period_end, trial_ends_at, cancelled_at, cancel_at_period_end, cancellation_reason, paused_at, pause_resumes_at, pause_reason, payment_method_type, nomba_token_key, dva_id, metadata, created_at, updated_at FROM subscriptions
WHERE merchant_id = $1
LIMIT $2 OFFSET $3
`

type GetAllSubscriptionsForMerchantParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) GetAllSubscriptionsForMerchant(ctx context.Context, arg GetAllSubscriptionsForMerchantParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, getAllSubscriptionsForMerchant, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.CustomerID,
			&i.CustomerEmail,
			&i.CustomerName,
			&i.PlanID,
			&i.Status,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.TrialEndsAt,
			&i.CancelledAt,
			&i.CancelAtPeriodEnd,
			&i.CancellationReason,
			&i.PausedAt,
			&i.PauseResumesAt,
			&i.PauseReason,
			&i.PaymentMethodType,
			&i.NombaTokenKey,
			&i.DvaID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, merchant_id, customer_id, customer_email, customer_name, plan_id, status, current_period_start, current_period_end, trial_ends_at, cancelled_at, cancel_at_period_end, cancellation_reason, paused_at, pause_resumes_at, pause_reason, payment_method_type, nomba_token_key, dva_id, metadata, created_at, updated_at FROM subscriptions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEndsAt,
		&i.CancelledAt,
		&i.CancelAtPeriodEnd,
		&i.CancellationReason,
		&i.PausedAt,
		&i.PauseResumesAt,
		&i.PauseReason,
		&i.PaymentMethodType,
		&i.NombaTokenKey,
		&i.DvaID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionForMerchantAndCustomer = `-- name: GetSubscriptionForMerchantAndCustomer :one
SELECT id, merchant_id, customer_id, customer_email, customer_name, plan_id, status, current_period_start, current_period_end, trial_ends_at, cancelled_at, cancel_at_period_end, cancellation_reason, paused_at, pause_resumes_at, pause_reason, payment_method_type, nomba_token_key, dva_id, metadata, created_at, updated_at FROM subscriptions
WHERE merchant_id = $1 AND customer_id = $2
`

type GetSubscriptionForMerchantAndCustomerParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	CustomerID string    `json:"customer_id"`
}

func (q *Queries) GetSubscriptionForMerchantAndCustomer(ctx context.Context, arg GetSubscriptionForMerchantAndCustomerParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionForMerchantAndCustomer, arg.MerchantID, arg.CustomerID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEndsAt,
		&i.CancelledAt,
		&i.CancelAtPeriodEnd,
		&i.CancellationReason,
		&i.PausedAt,
		&i.PauseResumesAt,
		&i.PauseReason,
		&i.PaymentMethodType,
		&i.NombaTokenKey,
		&i.DvaID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSubscriptionStatus = `-- name: SetSubscriptionStatus :exec
UPDATE subscriptions
SET status = $1
WHERE merchant_id = $2 AND customer_id = $3
`

type SetSubscriptionStatusParams struct {
	Status     SubscriptionStatus `json:"status"`
	MerchantID uuid.UUID          `json:"merchant_id"`
	CustomerID string             `json:"customer_id"`
}

func (q *Queries) SetSubscriptionStatus(ctx context.Context, arg SetSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, setSubscriptionStatus, arg.Status, arg.MerchantID, arg.CustomerID)
	return err
}

const storeDvaDetails = `-- name: StoreDvaDetails :one
UPDATE subscriptions
SET dva_id = $1
WHERE merchant_id = $2 AND customer_id = $3
RETURNING id, merchant_id, customer_id, customer_email, customer_name, plan_id, status, current_period_start, current_period_end, trial_ends_at, cancelled_at, cancel_at_period_end, cancellation_reason, paused_at, pause_resumes_at, pause_reason, payment_method_type, nomba_token_key, dva_id, metadata, created_at, updated_at
`

type StoreDvaDetailsParams struct {
	DvaID      pgtype.UUID `json:"dva_id"`
	MerchantID uuid.UUID   `json:"merchant_id"`
	CustomerID string      `json:"customer_id"`
}

func (q *Queries) StoreDvaDetails(ctx context.Context, arg StoreDvaDetailsParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, storeDvaDetails, arg.DvaID, arg.MerchantID, arg.CustomerID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEndsAt,
		&i.CancelledAt,
		&i.CancelAtPeriodEnd,
		&i.CancellationReason,
		&i.PausedAt,
		&i.PauseResumesAt,
		&i.PauseReason,
		&i.PaymentMethodType,
		&i.NombaTokenKey,
		&i.DvaID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const storeTokenKey = `-- name: StoreTokenKey :one
UPDATE subscriptions 
SET nomba_token_key = $1
WHERE merchant_id = $2 AND customer_id = $3
RETURNING id, merchant_id, customer_id, customer_email, customer_name, plan_id, status, current_period_start, current_period_end, trial_ends_at, cancelled_at, cancel_at_period_end, cancellation_reason, paused_at, pause_resumes_at, pause_reason, payment_method_type, nomba_token_key, dva_id, metadata, created_at, updated_at
`

type StoreTokenKeyParams struct {
	NombaTokenKey *string   `json:"nomba_token_key"`
	MerchantID    uuid.UUID `json:"merchant_id"`
	CustomerID    string    `json:"customer_id"`
}

func (q *Queries) StoreTokenKey(ctx context.Context, arg StoreTokenKeyParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, storeTokenKey, arg.NombaTokenKey, arg.MerchantID, arg.CustomerID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEndsAt,
		&i.CancelledAt,
		&i.CancelAtPeriodEnd,
		&i.CancellationReason,
		&i.PausedAt,
		&i.PauseResumesAt,
		&i.PauseReason,
		&i.PaymentMethodType,
		&i.NombaTokenKey,
		&i.DvaID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const storeTokenKeyBySubscriptionID = `-- name: StoreTokenKeyBySubscriptionID :one
UPDATE subscriptions
SET nomba_token_key = $2, updated_at = now()
WHERE id = $1
RETURNING id, merchant_id, customer_id, customer_email, customer_name, plan_id, status, current_period_start, current_period_end, trial_ends_at, cancelled_at, cancel_at_period_end, cancellation_reason, paused_at, pause_resumes_at, pause_reason, payment_method_type, nomba_token_key, dva_id, metadata, created_at, updated_at
`

type StoreTokenKeyBySubscriptionIDParams struct {
	ID            uuid.UUID `json:"id"`
	NombaTokenKey *string   `json:"nomba_token_key"`
}

func (q *Queries) StoreTokenKeyBySubscriptionID(ctx context.Context, arg StoreTokenKeyBySubscriptionIDParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, storeTokenKeyBySubscriptionID, arg.ID, arg.NombaTokenKey)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEndsAt,
		&i.CancelledAt,
		&i.CancelAtPeriodEnd,
		&i.CancellationReason,
		&i.PausedAt,
		&i.PauseResumesAt,
		&i.PauseReason,
		&i.PaymentMethodType,
		&i.NombaTokenKey,
		&i.DvaID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionDvaId = `-- name: UpdateSubscriptionDvaId :exec
UPDATE subscriptions
SET dva_id = $1
WHERE id = $2
`

type UpdateSubscriptionDvaIdParams struct {
	DvaID pgtype.UUID `json:"dva_id"`
	ID    uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateSubscriptionDvaId(ctx context.Context, arg UpdateSubscriptionDvaIdParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionDvaId, arg.DvaID, arg.ID)
	return err
}

const updateSubscriptionPeriodAndStatus = `-- name: UpdateSubscriptionPeriodAndStatus :one
UPDATE subscriptions
SET
    status = $2,
    current_period_start = $3,
    current_period_end = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, merchant_id, customer_id, customer_email, customer_name, plan_id, status, current_period_start, current_period_end, trial_ends_at, cancelled_at, cancel_at_period_end, cancellation_reason, paused_at, pause_resumes_at, pause_reason, payment_method_type, nomba_token_key, dva_id, metadata, created_at, updated_at
`

type UpdateSubscriptionPeriodAndStatusParams struct {
	ID                 uuid.UUID          `json:"id"`
	Status             SubscriptionStatus `json:"status"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) UpdateSubscriptionPeriodAndStatus(ctx context.Context, arg UpdateSubscriptionPeriodAndStatusParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionPeriodAndStatus,
		arg.ID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialEndsAt,
		&i.CancelledAt,
		&i.CancelAtPeriodEnd,
		&i.CancellationReason,
		&i.PausedAt,
		&i.PauseResumesAt,
		&i.PauseReason,
		&i.PaymentMethodType,
		&i.NombaTokenKey,
		&i.DvaID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
