// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertProcessedWebhookEvent = `-- name: InsertProcessedWebhookEvent :one
INSERT INTO processed_webhook_events (event_source, event_id, event_type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, event_source, event_id, event_type, payload, processed_at, processing_ms
`

type InsertProcessedWebhookEventParams struct {
	EventSource string `json:"event_source"`
	EventID     string `json:"event_id"`
	EventType   string `json:"event_type"`
	Payload     []byte `json:"payload"`
}

func (q *Queries) InsertProcessedWebhookEvent(ctx context.Context, arg InsertProcessedWebhookEventParams) (ProcessedWebhookEvent, error) {
	row := q.db.QueryRow(ctx, insertProcessedWebhookEvent,
		arg.EventSource,
		arg.EventID,
		arg.EventType,
		arg.Payload,
	)
	var i ProcessedWebhookEvent
	err := row.Scan(
		&i.ID,
		&i.EventSource,
		&i.EventID,
		&i.EventType,
		&i.Payload,
		&i.ProcessedAt,
		&i.ProcessingMs,
	)
	return i, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :one
INSERT INTO webhook_deliveries (
    merchant_id,
    subscription_id,
    event_type,
    payload,
    idempotency_key,
    webhook_url,
    status
) VALUES ($1, $2, $3, $4, $5, $6, 'pending')
RETURNING id, merchant_id, subscription_id, event_type, payload, idempotency_key, webhook_url, status, attempt_count, max_attempts, next_retry_at, last_attempt_at, last_http_status, created_at, delivered_at
`

type InsertWebhookDeliveryParams struct {
	MerchantID     uuid.UUID `json:"merchant_id"`
	SubscriptionID uuid.UUID `json:"subscription_id"`
	EventType      string    `json:"event_type"`
	Payload        []byte    `json:"payload"`
	IdempotencyKey string    `json:"idempotency_key"`
	WebhookUrl     string    `json:"webhook_url"`
}

func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, insertWebhookDelivery,
		arg.MerchantID,
		arg.SubscriptionID,
		arg.EventType,
		arg.Payload,
		arg.IdempotencyKey,
		arg.WebhookUrl,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.SubscriptionID,
		&i.EventType,
		&i.Payload,
		&i.IdempotencyKey,
		&i.WebhookUrl,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.LastAttemptAt,
		&i.LastHttpStatus,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}
